[package]
name = "spirit-tokio"
version = "0.6.0"
authors = ["Michal 'vorner' Vaner <vorner@vorner.cz>"]
description = "Tokio helpers for Spirit"
documentation = "https://docs.rs/spirit-tokio"
repository = "https://github.com/vorner/spirit"
license = "Apache-2.0 OR MIT"
readme = "README.md"
categories = ["config", "network-programming"]
keywords = ["async", "tokio", "service", "configuration", "spirit"]
edition = "2018"
include = [
    "Cargo.toml",
    "README.md",
    "src/**",
]

[features]
default = ["cfg-help"]
cfg-help = ["spirit/cfg-help", "structdoc"]

[badges]
travis-ci = { repository = "vorner/spirit" }
maintenance = { status = "actively-developed" }

[dependencies]
either = { version = "~1", optional = true }
err-context = "~0.1"
futures = "~0.1"
humantime = "~2"
log = "~0.4"
net2 = "~0.2"
serde = { version = "~1", features = ["derive"] }
serde-humantime = "~0.1"
spirit = { version = "~0.4.0", path = "..", default-features = false }
structdoc = { version = "~0.1", optional = true }
structopt = { version = "~0.3", default-features = false }
tk-listen = "~0.2"
tokio = "~0.1.8"

[dev-dependencies]
corona = "~0.4.1"
env_logger = "~0.7"
serde_json = "~1"
version-sync = "~0.9"
