[package]
name = "spirit-tokio"
version = "0.6.1"
authors = ["Michal 'vorner' Vaner <vorner@vorner.cz>"]
description = "Tokio helpers for Spirit"
documentation = "https://docs.rs/spirit-tokio"
repository = "https://github.com/vorner/spirit"
license = "Apache-2.0 OR MIT"
readme = "README.md"
categories = ["config", "network-programming"]
keywords = ["async", "tokio", "service", "configuration", "spirit"]
edition = "2018"
include = [
    "Cargo.toml",
    "README.md",
    "src/**",
]

[features]
default = ["cfg-help", "rt-from-cfg"]
cfg-help = ["spirit/cfg-help", "structdoc"]
rt-from-cfg = ["tokio/rt-threaded", "tokio/time", "tokio/io-driver"]

[badges]
travis-ci = { repository = "vorner/spirit" }
maintenance = { status = "actively-developed" }

[dependencies]
err-context = "~0.1"
log = "~0.4"
num_cpus = "~1"
serde = { version = "~1", features = ["derive"] }
spirit = { version = "~0.4.0", path = "..", default-features = false }
structdoc = { version = "~0.1", optional = true }
structopt = { version = "~0.3", default-features = false }

[dependencies.tokio]
# TODO: Make some/all these features optional (maybe default)?
version = "0.2"
default-features = false
features = ["macros", "rt-core", "sync"]

[dev-dependencies]
version-sync = "~0.9"
env_logger = "0.7"
